name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Fetch data
        run: |-
          set -euo pipefail
          < ./config.yaml envsubst > config-with-token.yaml
          cat config-with-token.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Run review-rot
        uses: lcarva/review-rot-action/run@main
        with:
          config: config-with-token.yaml
          output: output.json

      - name: Process data
        run: |-
          set -euo pipefail
          echo 'Full data set:'
          cat output.json

          mkdir web

          # TODO: filter data
          cp output.json web/data.json

      - name: Fetch review-rot web
        uses: lcarva/review-rot-action/web@main
        with:
          output: web

      - name: Debug
        run: |-
          set -euo pipefail
          tree web

      # TODO: Publish GitHub page (checkout review-rot repo first?)
