name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - run: |-
          set -euo pipefail
          < ./config.yaml envsubst > config-with-token.yaml
          cat config-with-token.yaml

      - name: Run review-rot
        uses: lcarva/review-rot@main
        with:
          config: config-with-token.yaml

      # TODO: Filter results
      # TODO: Publish GitHub page (checkout review-rot repo first?)
