name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # TODO: Run env subst script

      - name: Run review-rot
        uses: lcarva/review-rot@main
        with:
          config: ./config.yaml

      # TODO: Filter results
      # TODO: Publish GitHub page (checkout review-rot repo first?)
